# version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: gestionale-balle-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: on_gestionale_balle
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Europe/Rome
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: